// Calibrazioni tipografiche per il template Bold Corner.
// Valori verbatim da spec §5.3 — non modificare senza test visivi.
// NOTA: i valori per square differiscono dall'implementazione originale
// (padding 90 vs 80, corner 240 vs 200, num-box 24 vs 16 ecc.) — è intenzionale.
export const BOLD_CALIBRATIONS = {
  square: {
    padding:          '90px 80px 70px',
    corner_size:      '240px',
    slash_size:       '36px',
    slash_top:        '25px',
    num_size:         '24px',
    num_padding:      '10px 20px',
    kicker_size:      '18px',
    foot_padding_top: '24px',
    foot_name_size:   '22px',
    foot_meta_size:   '16px',
    body_archivo: {
      cover: { size: 110, line_height: 0.95 },
      xl:    { size: 92,  line_height: 0.98 },
      lg:    { size: 80,  line_height: 1.00 },
      md:    { size: 64,  line_height: 1.05 },
    },
    body_fraunces: {
      xl: { size: 86, line_height: 1.04 },
      lg: { size: 72, line_height: 1.04 },
    },
    divider_num:  { size: 340, top: 280 },
    cta_item:     { size: 80,  line_height: 1.0, gap: 22 },
    swipe_bottom: '120px',
    quote_attr:   { size: '20px', source_size: '17px', margin_top: '48px' },
  },
  portrait: {
    padding:          '120px 80px 100px',
    corner_size:      '280px',
    slash_size:       '40px',
    slash_top:        '30px',
    num_size:         '26px',
    num_padding:      '12px 22px',
    kicker_size:      '20px',
    foot_padding_top: '24px',
    foot_name_size:   '22px',
    foot_meta_size:   '16px',
    body_archivo: {
      cover: { size: 120, line_height: 0.95 },
      xl:    { size: 100, line_height: 1.00 },
      lg:    { size: 86,  line_height: 1.05 },
      md:    { size: 70,  line_height: 1.10 },
    },
    body_fraunces: {
      xl: { size: 94, line_height: 1.04 },
      lg: { size: 80, line_height: 1.04 },
    },
    divider_num:  { size: 380, top: 320 },
    cta_item:     { size: 86,  line_height: 1.0, gap: 26 },
    swipe_bottom: '150px',
    quote_attr:   { size: '24px', source_size: '20px', margin_top: '58px' },
  },
  landscape: {
    padding:          '55px 80px 45px',
    corner_size:      '180px',
    slash_size:       '26px',
    slash_top:        '18px',
    num_size:         '18px',
    num_padding:      '7px 14px',
    kicker_size:      '13px',
    foot_padding_top: '24px',
    foot_name_size:   '16px',
    foot_meta_size:   '12px',
    body_archivo: {
      cover: { size: 68, line_height: 1.00 },
      xl:    { size: 58, line_height: 1.05 },
      lg:    { size: 50, line_height: 1.05 },
      md:    { size: 42, line_height: 1.10 },
    },
    body_fraunces: {
      xl: { size: 54, line_height: 1.04 },
      lg: { size: 48, line_height: 1.04 },
    },
    divider_num:  { size: 180, top: 100 },
    cta_item:     { size: 48,  line_height: 1.0, gap: 14 },
    swipe_bottom: '70px',
    quote_attr:   { size: '15px', source_size: '13px', margin_top: '32px' },
  },
}
