// Calibrazioni tipografiche per il template Editorial Mark.
// Valori verbatim da spec §5.2 — non modificare senza test visivi.
// I valori quote (attr_size, attr_source_size, attr_margin_top) sono
// scalati proporzionalmente ai body_fraunces.xl poiché §5.2 non li specifica.
export const EDITORIAL_CALIBRATIONS = {
  square: {
    padding:           '90px 80px 70px',
    topline_top:       '60px',
    dot_top:           '54px',
    num_padding_top:   '18px',
    num_size:          '20px',
    kicker_size:       '18px',
    foot_padding_top:  '30px',
    foot_name_size:    '22px',
    foot_meta_size:    '16px',
    swipe_bottom:      '130px',
    body_archivo: {
      cover: { size: 118, line_height: 0.98 },
      xl:    { size: 96,  line_height: 1.00 },
      lg:    { size: 82,  line_height: 1.05 },
      md:    { size: 68,  line_height: 1.10 },
    },
    body_fraunces: {
      xl: { size: 92, line_height: 1.05 },
      lg: { size: 78, line_height: 1.05 },
      md: { size: 68, line_height: 1.10 },
    },
    divider_num:  { size: 340, top: 160 },
    cta_item:     { size: 88,  line_height: 1.05, gap: 18 },
    quote_attr:   { size: '30px', source_size: '26px', margin_top: '56px' },
  },
  portrait: {
    padding:           '120px 80px 100px',
    topline_top:       '75px',
    dot_top:           '69px',
    num_padding_top:   '24px',
    num_size:          '20px',
    kicker_size:       '18px',
    foot_padding_top:  '32px',
    foot_name_size:    '22px',
    foot_meta_size:    '16px',
    swipe_bottom:      '160px',
    body_archivo: {
      cover: { size: 128, line_height: 0.95 },
      xl:    { size: 104, line_height: 1.00 },
      lg:    { size: 88,  line_height: 1.08 },
      md:    { size: 74,  line_height: 1.12 },
    },
    body_fraunces: {
      xl: { size: 100, line_height: 1.05 },
      lg: { size: 84,  line_height: 1.05 },
      md: { size: 74,  line_height: 1.12 },
    },
    divider_num:  { size: 380, top: 200 },
    cta_item:     { size: 94,  line_height: 1.05, gap: 22 },
    quote_attr:   { size: '34px', source_size: '28px', margin_top: '64px' },
  },
  landscape: {
    padding:           '55px 80px 45px',
    topline_top:       '30px',
    dot_top:           '24px',
    num_padding_top:   '10px',
    num_size:          '16px',
    kicker_size:       '13px',
    foot_padding_top:  '16px',
    foot_name_size:    '16px',
    foot_meta_size:    '12px',
    swipe_bottom:      '80px',
    body_archivo: {
      cover: { size: 72, line_height: 1.00 },
      xl:    { size: 60, line_height: 1.05 },
      lg:    { size: 52, line_height: 1.05 },
      md:    { size: 44, line_height: 1.10 },
    },
    body_fraunces: {
      xl: { size: 58, line_height: 1.05 },
      lg: { size: 50, line_height: 1.05 },
      md: { size: 44, line_height: 1.10 },
    },
    divider_num:  { size: 180, top: 80 },
    cta_item:     { size: 54,  line_height: 1.05, gap: 12 },
    quote_attr:   { size: '20px', source_size: '16px', margin_top: '36px' },
  },
}
